"""
Generates docs/wiki/generated/complexity.md: a table of the worst files in
src/app by cyclomatic complexity, plus a Mermaid pie chart of the cyclomatic
complexity RANK distribution -- both computed directly from `radon`'s Python
API against the real, current source tree. Regenerated on every
`make wiki`/`make wiki-build`, so it always reflects the code as it actually
is today, not a one-time snapshot.

The pie chart deliberately charts complexity rank, not maintainability-index
rank: MI is dominated by file size, and this codebase's files are all small
by design, so an MI-rank chart is a single 100% "A" slice with zero
information. Complexity rank has real spread even in this codebase's own
top-15 table (A/B/C all appear), so it's the one worth visualizing.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from radon.complexity import cc_rank, cc_visit
from radon.metrics import mi_rank, mi_visit

_MERMAID_INIT = (
    '%%{init: {"theme": "default", "themeVariables": {"fontSize": "14px"}, '
    '"flowchart": {"nodeSpacing": 20, "rankSpacing": 16, "padding": 10, '
    '"subGraphTitleMargin": {"top": 5, "bottom": 12}, "useMaxWidth": false}}}%%'
)

_SRC_ROOT = Path(__file__).resolve().parents[2] / "src" / "app"
_OUTPUT_PATH = Path(__file__).resolve().parents[2] / "docs" / "wiki" / "generated" / "complexity.md"
_TOP_N = 15


@dataclass(frozen=True, slots=True)
class FileComplexity:
    path: str
    max_complexity: int
    worst_block_name: str
    maintainability_index: float


def analyze_file(code: str, relative_path: str) -> FileComplexity:
    """
    Runs radon's cyclomatic-complexity visitor and maintainability-index
    calculation directly against a source string -- no subprocess, no CLI.
    """
    blocks = cc_visit(code)
    if blocks:
        worst = max(blocks, key=lambda block: block.complexity)
        max_complexity = int(worst.complexity)
        worst_block_name = worst.fullname if hasattr(worst, "fullname") else worst.name
    else:
        max_complexity = 0
        worst_block_name = "-"

    maintainability_index = mi_visit(code, True)

    return FileComplexity(
        path=relative_path,
        max_complexity=max_complexity,
        worst_block_name=worst_block_name,
        maintainability_index=maintainability_index,
    )


def analyze_directory(root: Path, relative_to: Path) -> list[FileComplexity]:
    results = []
    for py_file in sorted(root.rglob("*.py")):
        code = py_file.read_text()
        relative_path = py_file.relative_to(relative_to).as_posix()
        results.append(analyze_file(code, relative_path))
    return results


def render_markdown(results: list[FileComplexity]) -> str:
    if not results:
        return (
            "<!-- AUTO-GENERATED by scripts/wiki/complexity_report.py -- "
            "do not edit by hand. -->\n\nNo Python files were found to analyze.\n"
        )

    worst_first = sorted(results, key=lambda r: r.max_complexity, reverse=True)[:_TOP_N]
    table_rows = "\n".join(
        f"    | `{r.path}` | {r.max_complexity} ({cc_rank(r.max_complexity)}) | `{r.worst_block_name}` "
        f"| {r.maintainability_index:.1f} ({mi_rank(r.maintainability_index)}) |"
        for r in worst_first
    )

    cc_rank_counts: dict[str, int] = {}
    for r in results:
        rank = cc_rank(r.max_complexity)
        cc_rank_counts[rank] = cc_rank_counts.get(rank, 0) + 1
    # radon's own A-F order, not insertion order, so the legend always reads
    # best-to-worst regardless of which ranks this codebase actually has.
    pie_slices = "\n".join(f'        "{rank}" : {cc_rank_counts[rank]}' for rank in "ABCDEF" if rank in cc_rank_counts)

    ranks_note = (
        '"Rank" here is `radon`\'s own A-F (complexity) / A-C (maintainability index) letter grades — A is best '
        "in both cases. A file with a high complexity rank isn't automatically a problem (a router with many "
        "mapped exception types is inherently branchy) — treat this as a place to look, not an automatic verdict."
    )
    chart_note = (
        'Each file is ranked by its single worst function/class (the same "max cyclomatic complexity" column as '
        "the table above) — A (1-5, simple), B (6-10, well-structured), C (11-20, moderate risk), through F "
        "(41+, error-prone). Maintainability index isn't charted here: it's dominated by file size, and this "
        'codebase\'s files are small by design, so every file scores in the top "A" band — a real property of '
        "this codebase, but not one a pie chart can show anything useful about."
    )

    return f"""<!-- AUTO-GENERATED by scripts/wiki/complexity_report.py -- do not edit by hand.
     Regenerated on every `make wiki`/`make wiki-build` from the real current
     contents of `src/app`, via `radon`'s Python API. -->

!!! figure "Worst {len(worst_first)} files in `src/app` by cyclomatic complexity"
    | File | Max cyclomatic complexity (rank) | Worst block | Maintainability index (rank) |
    |---|---|---|---|
{table_rows}

    > {ranks_note}

!!! figure "Cyclomatic complexity rank distribution across every file in src/app ({len(results)} files)"
    ```mermaid
    {_MERMAID_INIT}
    pie showData
        title Cyclomatic complexity rank (A best, F worst)
{pie_slices}
    ```

    > {chart_note}
"""


def main() -> None:
    results = analyze_directory(_SRC_ROOT, relative_to=_SRC_ROOT.resolve().parents[1])
    content = render_markdown(results)
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(content)
    print(f"Wrote {_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
