"""add description to organizations

Revision ID: 1a001c1d415f
Revises: 7a58c0ff9aec
Create Date: 2026-10-03 01:03:21.946948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a001c1d415f"
down_revision: Union[str, Sequence[str], None] = "7a58c0ff9aec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organizations", sa.Column("description", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "description")
    # ### end Alembic commands ###
