"""add email and phone number to users

Revision ID: 16620e21528f
Revises: c025baa8044e
Create Date: 2026-07-30 19:57:20.772221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16620e21528f"
down_revision: Union[str, Sequence[str], None] = "c025baa8044e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=254), nullable=False))
    op.add_column("users", sa.Column("phone_number", sa.String(length=11), nullable=False))
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    op.create_unique_constraint(op.f("uq_users_phone_number"), "users", ["phone_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_phone_number"), "users", type_="unique")
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
