"""add expires_at to organization_memberships

Revision ID: 7a58c0ff9aec
Revises: 2e2d0e039056
Create Date: 2026-09-28 21:27:00.916707

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a58c0ff9aec"
down_revision: Union[str, Sequence[str], None] = "2e2d0e039056"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization_memberships", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_memberships", "expires_at")
    # ### end Alembic commands ###
